steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'get-key'
    entrypoint: 'bash'
    dir: .
    args:
      - '-c'
      - |
        gcloud secrets versions access ${_GITHUB_KEY_VERSION} --secret="github" --project=${_GITHUB_KEY_PROJECT_ID} > /root/.ssh/id_rsa
    volumes:
      - name: 'ssh'
        path: /root/.ssh
  - name: 'gcr.io/cloud-builders/git'
    id: 'add-key'
    entrypoint: 'bash'
    dir: .
    args:
      - '-c'
      - |
        chmod 600 /root/.ssh/id_rsa
        cat <<EOF >/root/.ssh/config
        Hostname github.com
        IdentityFile /root/.ssh/id_rsa
        EOF
        ssh-keyscan -t rsa github.com > /root/.ssh/known_hosts
    volumes:
      - name: 'ssh'
        path: /root/.ssh
  - name: 'gcr.io/cloud-builders/git'
    id: 'crlf'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        git config --global core.autocrlf input
        git reset --hard
        git clean -fdx
        refs=$(git config hooks.protected-branch.refs)
        echo $(git rev-parse --abbrev-ref HEAD)
        ls -la
    volumes:
      - name: 'ssh'
        path: /root/.ssh



options:
  substitution_option: 'ALLOW_LOOSE'

substitutions:
  _GITHUB_KEY_PROJECT_ID: "cb-test-342002"
  _GITHUB_KEY_VERSION: "latest"
  _BASE_BRANCH: "main"
  _BUILD_SA: "bilayer-sa"

timeout: 600s
